language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=rhel6

install:
  - pip install tox

script:
  - tox

branches:
  only:
    - master

notifications:
  email:
    - taxii-commits-list@lists.mitre.org
